FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy project file for restore caching
COPY ["Filewritetask.csproj", "."]
RUN dotnet restore "./Filewritetask.csproj"

# Copy the rest of the source
COPY . .
WORKDIR /app

# Publish
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Filewritetask.dll"]